[package]
name = "knhk-aot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
path = "src/lib.rs"

[dependencies]
rio_turtle = { version = "0.8.5", default-features = false }
rio_api = { version = "0.8.5", default-features = false }

[features]
default = []
std = []
