[book]
title = "KNHKS - Knowledge Hook System"
authors = ["KNHKS Core Team"]
description = "8-Tick Hot Path Knowledge Graph Query System - Production-Ready Documentation"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/seanchatmangpt/ggen"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/seanchatmangpt/ggen/edit/master/vendors/knhks/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.math]
render = "katex"
preview = true

[output.html.redirect]
"index.html" = "intro.html"

[preprocessor.links]

